# Generated by Django 5.2 on 2025-05-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_incidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='further_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
