# Generated by Django 5.2 on 2025-05-29 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_further_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='further_description',
        ),
    ]
